### ISSUE TITLE
failure when deploying 3 x (region + rack)

### ISSUE THREAD

**Issue by marosg42** [maas/maas-ansible-playbook#65]
As discussed with @cpg1111 - maas initialization step fails

Here is an output from -vvv as requested

[output.txt](https://github.com/maas/maas-ansible-playbook/files/10346856/output.txt)

**Comment by marosg42** [comment]
```
all:
    children:
        maas_region_controller:
            hosts:
                10.244.40.30:
                    ansible_user: ubuntu
                    admin_username: "root"
                    admin_password: "root"
                    admin_email: "admin@email.com"
                    admin_id: "admin"
                    maas_version: 3.2
                    maas_installation_type: snap 
                    maas_url: http://10.244.40.33:5240/MAAS
                10.244.40.31:
                    ansible_user: ubuntu
                    admin_username: "root"
                    admin_password: "root"
                    admin_email: "admin@email.com"
                    admin_id: "admin"
                    maas_version: 3.2
                    maas_installation_type: snap 
                    maas_url: http://10.244.40.33:5240/MAAS
                10.244.40.32:
                    ansible_user: ubuntu
                    admin_username: "root"
                    admin_password: "root"
                    admin_email: "admin@email.com"
                    admin_id: "admin"
                    maas_version: 3.2
                    maas_installation_type: snap 
                    maas_url: http://10.244.40.33:5240/MAAS
        maas_rack_controller:
            hosts:
                10.244.40.30:
                    ansible_user: ubuntu
                10.244.40.31:
                    ansible_user: ubuntu
                10.244.40.32:
                    ansible_user: ubuntu
        maas_postgres:
            children:
                maas_postgres_primary:
                    hosts:
                        10.244.40.30:
                            ansible_user: ubuntu
                            maas_postgres_password: example
                maas_postgres_secondary:
                    hosts:
                        10.244.40.31:
                            ansible_user: ubuntu
                            maas_postgres_password: example
                        10.244.40.32:
                            ansible_user: ubuntu
                            maas_postgres_password: example
        maas_proxy:
            hosts:
                10.244.40.33:
                    ansible_user: ubuntu
```
