### ISSUE TITLE
Bad Gateway after reboot with multipass

### ISSUE THREAD

**Issue by bcdiaconu** [maas/maas-ansible-playbook#68]
Created a ubuntu VM on windows with multipass. I also create a bridge by use of multipass cli arguments.

Configured the hosts file. Than ran the ansible playbook with `maas_url` set to the bridged external ethernet adapter, `maas_version` set to `3.2` and `maas_instalation_type` set to `snap`.
After successful run of the playbook, maas is working initially. 

But after reboot, it will error out with message `The server connection failed with the error "Bad Gateway"`

**Comment by bcdiaconu** [comment]
The same behavior is with `maas_version` set to `3.3` from `candidate` channel.

**Comment by bcdiaconu** [comment]
I saw that iptables rules are not persistent between restarts

**Comment by bcdiaconu** [comment]
a solution to look into:

```yaml
---
- name: Configure iptables
  hosts: all
  become: true

  tasks:
    - name: Install iptables-persistent package
      apt:
        name: iptables-persistent
        state: present

    - name: Save iptables rules
      shell: netfilter-persistent save
```
