### ISSUE TITLE
Iptables not persistent

### ISSUE THREAD

**Issue by bcdiaconu** [maas/maas-ansible-playbook#85]
iptables rules are cleared after reboot. A persistent iptables should be achieved. 

For Debian based systems, iptables-persistent is a good option.

```yaml
- name: Install iptables-persistent
  hosts: all
  become: true
  tasks:
    - name: Install iptables-persistent
      ansible.builtin.apt:
        name: iptables-persistent
        state: present
      changed_when: false

- name: Configure iptables rules
  hosts: all
  become: true
  tasks:
    - name: Set up iptables rules
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
      changed_when: false

    - name: Save iptables rules
      ansible.builtin.shell: netfilter-persistent save
      changed_when: false
```
